<?php
require_once __DIR__ . '/includes/bootstrap.php';
requireAccess('distribuicao');
$db = getDB();
$clienteId = query_int('cliente_id', 0, 0);
$equipamentoId = query_int('equipamento_id', 0, 0);
$tipo = trim((string) get_query('tipo', ''));
$page = query_int('page', 1, 1);
$perPage = 25;
$allowedIds = distribuicao_allowed_client_ids('visualizar');
if ($clienteId > 0) distribuicao_require_cliente_access($clienteId, 'visualizar');
if ($equipamentoId > 0) { $equip = distribuicao_fetch_equipamento($equipamentoId); if ($equip) distribuicao_require_cliente_access((int)$equip['cliente_id'], 'visualizar'); }
$where=['1=1']; $params=[];
if (($_SESSION['perfil'] ?? '') !== 'admin') { if (empty($allowedIds)) $where[]='1=0'; else $where[]='m.cliente_id IN (' . implode(',', array_map('intval',$allowedIds)) . ')'; }
if ($clienteId > 0) { $where[]='m.cliente_id = :cliente_id'; $params[':cliente_id']=$clienteId; }
if ($equipamentoId > 0) { $where[]='m.equipamento_id = :equipamento_id'; $params[':equipamento_id']=$equipamentoId; }
if ($tipo !== '') { $where[]='m.tipo_movimentacao = :tipo'; $params[':tipo']=$tipo; }
$countStmt=$db->prepare('SELECT COUNT(*) FROM distribuicao_movimentacoes m WHERE ' . implode(' AND ',$where)); $countStmt->execute($params); $totalRows=(int)$countStmt->fetchColumn(); $pagination=paginate($totalRows,$page,$perPage);
$sql='SELECT m.*, c.nome AS cliente_nome, e.modelo, e.serie FROM distribuicao_movimentacoes m LEFT JOIN distribuicao_clientes c ON c.id = m.cliente_id LEFT JOIN distribuicao_equipamentos e ON e.id = m.equipamento_id WHERE ' . implode(' AND ',$where) . ' ORDER BY m.data_movimentacao DESC, m.id DESC LIMIT :limit OFFSET :offset';
$stmt=$db->prepare($sql); foreach($params as $k=>$v){$stmt->bindValue($k,$v);} $stmt->bindValue(':limit',$pagination['per_page'],PDO::PARAM_INT); $stmt->bindValue(':offset',$pagination['offset'],PDO::PARAM_INT); $stmt->execute(); $rows=$stmt->fetchAll() ?: []; $clientes=distribuicao_accessible_clients('visualizar');
include 'includes/header.php'; echo render_flash();
?>
<div class="page-head"><div class="page-head-copy"><h2>Movimentações da distribuição</h2><p>Histórico de instalação, troca técnica, remanejamento, desinstalação e mudanças de status.</p></div><div class="page-head-actions"><a href="distribuicao_index.php" class="btn btn-ghost"><?= icon('printer') ?> Voltar ao parque</a></div></div>
<div class="card" style="padding:0;overflow:hidden"><form method="get" class="toolbar-shell"><div class="toolbar-field"><select name="cliente_id"><option value="0">Todos os clientes</option><?php foreach($clientes as $cliente): ?><option value="<?= (int)$cliente['id'] ?>" <?= $clienteId === (int)$cliente['id'] ? 'selected' : '' ?>><?= e($cliente['nome']) ?></option><?php endforeach; ?></select></div><div class="toolbar-field"><select name="tipo"><option value="">Todos os tipos</option><?php foreach(distribuicao_tipo_movimentacao_options() as $key=>$label): ?><option value="<?= e($key) ?>" <?= $tipo === $key ? 'selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></div><div class="toolbar-field"><input type="number" name="equipamento_id" value="<?= $equipamentoId ?: '' ?>" placeholder="ID equipamento"></div><div class="toolbar-actions"><button type="submit" class="btn btn-ghost btn-sm"><?= icon('filter') ?> Filtrar</button><a href="distribuicao_movimentacoes.php" class="btn btn-ghost btn-sm">Limpar</a></div></form><div class="table-wrap"><table><thead><tr><th>Data</th><th>Cliente</th><th>Tipo</th><th>Equipamento</th><th>Alteração</th><th>Técnico</th><th>Observações</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td class="mono"><?= $row['data_movimentacao'] ? date('d/m/Y', strtotime($row['data_movimentacao'])) : '—' ?></td><td><strong><?= e($row['cliente_nome'] ?: '—') ?></strong></td><td><span class="badge b-neutral"><?= e(distribuicao_tipo_movimentacao_options()[$row['tipo_movimentacao']] ?? $row['tipo_movimentacao']) ?></span></td><td><strong>#<?= (int)$row['equipamento_id'] ?></strong><div class="sub"><?= e($row['modelo'] ?: '—') ?> · <?= e($row['serie'] ?: '—') ?></div></td><td class="sub"><?php if ($row['serie_antiga'] || $row['serie_nova']): ?>Série: <?= e($row['serie_antiga'] ?: '—') ?> → <?= e($row['serie_nova'] ?: '—') ?><br><?php endif; ?><?php if ($row['status_anterior'] || $row['status_novo']): ?>Status: <?= e($row['status_anterior'] ?: '—') ?> → <?= e($row['status_novo'] ?: '—') ?><br><?php endif; ?><?php if ($row['monitoramento_anterior'] || $row['monitoramento_novo']): ?>Monitoramento: <?= e($row['monitoramento_anterior'] ?: '—') ?> → <?= e($row['monitoramento_novo'] ?: '—') ?><?php endif; ?></td><td><?= e($row['tecnico_responsavel'] ?: '—') ?></td><td class="sub"><?= e($row['observacoes'] ?: ($row['motivo'] ?: '—')) ?></td></tr><?php endforeach; ?><?php if (!$rows): ?><tr><td colspan="7" style="padding:24px;text-align:center;color:var(--muted)">Nenhuma movimentação encontrada.</td></tr><?php endif; ?></tbody></table></div><?= render_pagination($pagination) ?></div>
